backend/models/PollsAnswer.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "polls_answer".
 *
 * @property integer $id
 * @property integer $id_poll
 * @property string $answer
 */
class PollsAnswer extends \yii\db\ActiveRecord
{

    public $laravel;
    public $yii2;
    public $CI;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'polls_answer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'answer'], 'required'],
            ['id', 'integer'],
            [['answer'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'answer' => 'Answer',
        ];
    }
}

frontend/models/PollsAnswer.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "polls_answer".
 *
 * @property integer $id
 * @property integer $id_poll
 * @property string $answer
 */
class PollsAnswer extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'polls_answer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'answer'], 'required'],
            ['id','integer'],
            [['answer'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'answer' => 'Answer',
        ];
    }

    public function getAnswerOptions()
    {
        return [
            '0' => 'Laravel',
            '1' => 'Yii',
            '2' => 'CI',
        ];
    }
}

backend/controllers/PollsAnswerController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\PollsAnswer;
use backend\models\PollsAnswerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PollsAnswerController implements the CRUD actions for PollsAnswer model.
 */
class PollsAnswerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PollsAnswer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PollsAnswerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PollsAnswer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PollsAnswer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PollsAnswer();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PollsAnswer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PollsAnswer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PollsAnswer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PollsAnswer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PollsAnswer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/PollsAnswerController.php
<?php

namespace frontend\controllers;

use frontend\models\PollsAnswer;
use frontend\models\PollsAnswerSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * PollsAnswerController implements the CRUD actions for PollsAnswer model.
 */
class PollsAnswerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PollsAnswer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PollsAnswerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    // public function actionAnswer()
    // {
    //    $sql = SELECT answer, COUNT(answer) FROM polls_answer GROUP BY answer;
    //    $connection = Yii::app()->db;
    //    $command = $connection->createCommand($sql);
    //    $row = $command->queryAll();

    //    $this->render('index',array(
    //     'row' => $row,
    // ));

    // }

    public function actionIndexAjaxBarChart()
    {
        $data = [];

        $answerOptions = PollsAnswer::getAnswerOptions();
        $pollsAnswers = PollsAnswer::find()->select(['answer', 'COUNT(id) AS total_answer'])->groupBy(['answer'])->asArray()->all();
        if ($pollsAnswers) {
            foreach ($pollsAnswers as $pollsAnswer) {
                $answerName = $answerOptions[$pollsAnswer['answer']];

                $data[] = [
                    $answerName,
                    (int) $pollsAnswer['total_answer']
                ];
            }
        }

        $this->asJson($data);
    }

    public function actionIndexAjaxPieChart()
    {
        $data = [];

        $answerOptions = PollsAnswer::getAnswerOptions();
        $pollsAnswers = PollsAnswer::find()->select(['answer', 'COUNT(id) AS total_answer'])->groupBy(['answer'])->asArray()->all();
        if ($pollsAnswers) {
            foreach ($pollsAnswers as $pollsAnswer) {
                $answerName = $answerOptions[$pollsAnswer['answer']];

                $data[] = [
                    'name' => $answerName,
                    'y' => (int) $pollsAnswer['total_answer']
                ];
            }
        }

        $this->asJson($data);
    }

    /**
     * Displays a single PollsAnswer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PollsAnswer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PollsAnswer();

        if ($model->load(Yii::$app->request->post()) ) {
            //$model->answer=$_POST['pilihanmu'];
            $model->save();
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PollsAnswer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PollsAnswer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PollsAnswer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PollsAnswer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PollsAnswer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    }

frontend/views/polls-answer/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\PollsAnswer */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="polls-form">

    <?php $form = ActiveForm::begin(); ?>
    
       <label class="control-label" for="modelname-attributename"><h3>Apa Framework yang anda sukai?</h3></label>
    
    <br>
    <?= $form->field($model, 'answer')->radioList( 
    					[
    						'0'=>'Laravel', 
    						'1' => 'yii2', 
    						'2' => 'CI'
    					],
    					['separator' => '<br>']
    						 );?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Submit' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/polls-answer/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\PollsAnswerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="polls-answer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'answer') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/polls-answer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\PollsAnswer */

$this->title = 'Create Polls Answer';
$this->params['breadcrumbs'][] = ['label' => 'Polls Answers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="polls-answer-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/polls-answer/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JqueryAsset;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\PollsAnswerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Polls Result';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="polls-answer-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div id="bar_chart" data-url="<?= Url::to(['polls-answer/index-ajax-bar-chart']) ?>"></div>
    <div id="pie_chart" data-url="<?= Url::to(['polls-answer/index-ajax-pie-chart']) ?>"></div>

    <p>
        <?= Html::a('start Polls Answer', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
   <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        // 'columns' => [
        //     ['class' => 'yii\grid\SerialColumn'],

        //     // 'id',
        //     'answer:ntext',

        //     ['class' => 'yii\grid\ActionColumn'],
        // ],
    ]); ?>
    <label class="control-label" for="keterangan"><h4>keterangan :</h4></label><br>
    <label class="control-label" for="keterangan"><h4>0 untuk Laravel</h4></label><br>
    <label class="control-label" for="keterangan"><h4>1 untuk yii2</h4></label><br>
    <label class="control-label" for="keterangan"><h4>2 untuk CI</h4></label>

</div>

<?php
$this->registerJsFile('https://code.highcharts.com/highcharts.js', ['depends' => [JqueryAsset::className()], 'position' => View::POS_END]);
$this->registerJsFile('@web/js/polls-answer/index.js', ['depends' => [JqueryAsset::className()], 'position' => View::POS_END]);
?>

frontend/views/polls-answer/stus.php
<?php
$this->breadcrumbs=array(
	'Chart'=>array('index'),
	'Statistik Pengguna',
);

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'tinstrument-form',
	'enableAjaxValidation'=>false,
)); ?>
<center>
?>
<?php
$label=array();
$nilai=array();

foreach($dataProvider->getData() as $i=>$ii)
{
    $label[$i]=$ii['aa'];
    $nilai[$i]=(int)$ii['count(id)'];
}

$this->widget('application.extensions.highcharts.HighchartsWidget', array(
   'options'=>array(
     'chart'=> array('defaultSeriesType'=>'column',),
      'title' => array('text' => ''),
      'legend'=>array('enabled'=>false),
      'xAxis'=>array('categories'=>$label,
			'title'=>array('text'=>''),),
      'yAxis'=> array(
            'min'=> 0,
            'title'=> array(
            'text'=>'Jumlah'
            ),
        ),
      'series' => array(
         array('data' => $nilai)
      ),
      'tooltip' => array('formatter' => 'js:function(){ return "<b>"+this.point.name+"</b> :"+this.y; }'),
      'tooltip' => array(
		'formatter' => 'js:function() {return "<b>"+ this.x +"</b><br/>"+"Jumlah : "+ this.y; }'
      ),
      'plotOptions'=>array('pie'=>(array(
                    'allowPointSelect'=>true,
                    'showInLegend'=>true,
                    'cursor'=>'pointer',
                )
            )                       
        ),
      'credits'=>array('enabled'=>false),
   )
));

?>
</center>
<?php $this->endWidget(); ?>

frontend/views/polls-answer/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\PollsAnswer */

$this->title = 'Update Polls Answer: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Polls Answers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="polls-answer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/polls-answer/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\PollsAnswer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Polls Answers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="polls-answer-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'answer:ntext',
        ],
    ]) ?>

</div>